const LogTypes = {
  LOG_GET_ALL: 'LOG_GET_ALL',
  LOG_GET_ALL_SUCCESS: 'LOG_GET_ALL_SUCCESS',
  LOG_GET_ALL_FAILED: 'LOG_GET_ALL_FAILED',
  LOG_ARCHIVE: 'LOG_ARCHIVE',
  LOG_ARCHIVE_SUCCESS: 'LOG_ARCHIVE_SUCCESS',
  LOG_ARCHIVE_FAILED: 'LOG_ARCHIVE_FAILED'
};

export { LogTypes };